### PR TITLE
Removed Git coupling from deployment script

### PR DESCRIPTION
**Pull request by portovep**
I think it would be nice that our deployment script does not depend on having Git installed and having authorisation to access the remote repo. It would allow to deploy the app to a server using commands like scp or curl and not only git clone.

### CODE REVIEW

**Comment by vise890** [comment]
I agree and I like the idea. At that point why don't we keep this open, and continue on bringing the full build on the local dev machine.

What about having a `:build` `lein` task that replaces the `deploy.sh` script and pushes to the server via `scp`. We can store the credentials in `profiles.clj` (which is loaded already in `project.clj by Leiningen) and`.gitignore` it.

What do you think?

**Comment by portovep** [comment]
Sounds good to me. I will put us in a position where we could even use SnapCI to automate the deployment of the latest build to our server every time we merge a pull request or push.

**Comment by vise890** [comment]
Ok, so because we can't all push to your branch, instead of merging straight to master, i've merged into a topic branch in #14 . That way we can both clone the repo and propose changes. I've also opened #15 which is a replacement of this PR so that we can continue working on it.

Sounds good?

**Comment by portovep** [comment]
Good to me. I will try to find some time to work on it.

**Pull request closed without merging**
